version: "3"
services:
  app:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT
      - DB_ROOT_PASSWORD
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_PROTOCOL
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/app
    command: ["/app/start.sh"]
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      - DB_ROOT_PASSWORD
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_CONTAINER_NAME
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    volumes:
      - data.dev:/var/lib/mysql

volumes:
  data.dev:
    driver: local
