version: "3"
services:
  app:
    container_name: go-api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - PORT
      - DB_ROOT_PASSWORD
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_PROTOCOL
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/app
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    volumes:
      - ./server/db:/var/lib/mysql
