version: "3"
services:
  app:
    container_name: go-api
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - PORT
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    command: ["./build/start.sh"]
