version: "3"
services:
  app:
    container_name: go-api
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: ["./start.sh"]
